
OPENAI_API_KEY:
OPENAI_API_BASE: https://api.aikey.one/v1
DATA_LIST: Android,Apache,BGL,Hadoop,HDFS,HealthApp,HPC,Linux,Mac,OpenSSH,OpenStack,Proxifier,Spark,Thunderbird,Windows,Zookeeper
BASE_PROMPT: 您是一个问答对生成器。我提供了相关的文本片段以及流程内容。您需要生成一个问题和相应的答案，并确保问题和答案都基于上下文。如果无法生成问题，请回复“当前语句段无法生成问题。”在回答中不要包含过于个人化的内容。请记住，您只能根据提供的内容来生成问题与答案。必须使用Chinese进行回应。
PARSE_SETTING:
  HDFS:
    log_file: "HDFS_2k.log"
    log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"
    regex:
      - "blk_-?\\d+"
      - "(\\d+\\.){3}\\d+(:\\d+)?"
    st: 0.5
    depth: 4
  Hadoop:
    log_file: "Hadoop_2k.log"
    log_format: "<Date> <Time> <Level> \\[<Process>\\] <Component>: <Content>"
    regex:
      - "(\\d+\\.){3}\\d+"
    st: 0.5
    depth: 4
  Spark:
    log_file: "Spark_2k.log"
    log_format: "<Date> <Time> <Level> <Component>: <Content>"
    regex:
      - "(\\d+\\.){3}\\d+"
      - "\\b[KGTM]?B\\b"
      - "([\\w-]+\\.){2,}[\\w-]+"
    st: 0.5
    depth: 4
  Zookeeper:
    log_file: "Zookeeper_2k.log"
    log_format: "<Date> <Time> - <Level>  \\[<Node>:<Component>@<Id>\\] - <Content>"
    regex:
      - "(/|)(\\d+\\.){3}\\d+(:\\d+)?"
    st: 0.5
    depth: 4
  BGL:
    log_file: "BGL_2k.log"
    log_format: "<Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>"
    regex:
      - "core\\.\\d+"
    st: 0.5
    depth: 4
  HPC:
    log_file: "HPC_2k.log"
    log_format: "<LogId> <Node> <Component> <State> <Time> <Flag> <Content>"
    regex:
      - "=\\d+"
    st: 0.5
    depth: 4
  Thunderbird:
    log_file: "Thunderbird_2k.log"
    log_format: "<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>(\\[<PID>\\])?: <Content>"
    regex:
      - "(\\d+\\.){3}\\d+"
    st: 0.5
    depth: 4
  Windows:
    log_file: "Windows_2k.log"
    log_format: "<Date> <Time>, <Level> <Component>  <Content>"
    regex:
      - "0x.*?\\s"
    st: 0.7
    depth: 5
  Linux:
    log_file: "Linux_2k.log"
    log_format: "<Month> <Date> <Time> <Level> <Component>(\\[<PID>\\])?: <Content>"
    regex:
      - "(\\d+\\.){3}\\d+"
      - "\\d{2}:\\d{2}:\\d{2}"
    st: 0.39
    depth: 6
  Android:
    log_file: "Android_2k.log"
    log_format: "<Date> <Time>  <Pid>  <Tid> <Level> <Component>: <Content>"
    regex:
      - "(/[\\w-]+)+"
      - "([\\w-]+\\.){2,}[\\w-]+"
      - "\\b(\\-?\\+?\\d+)\\b|\\b0[Xx][a-fA-F\\d]+\\b|\\b[a-fA-F\\d]{4,}\\b"
    st: 0.2
    depth: 6
  HealthApp:
    log_file: "HealthApp_2k.log"
    log_format: "<Time>\\|<Component>\\|<Pid>\\|<Content>"
    regex: []
    st: 0.2
    depth: 4
  Apache:
      log_file: "Apache_2k.log"
      log_format: "\\[<Time>\\] \\[<Level>\\] <Content>"
      regex:
          - "(\\d+\\.){3}\\d+"
      st: 0.5
      depth: 4
  Proxifier:
      log_file: "Proxifier_2k.log"
      log_format: "\\[<Time>\\] <Program> - <Content>"
      regex:
          - "<\\d+\\ssec"
          - "([\\w-]+\\.){2,}[\\w-]+(:\\d+)?"
          - "\\d{2}:\\d{2}(:\\d{2})*"
          - "[KGTM]B"
      st: 0.6
      depth: 3
  OpenSSH:
      log_file: "OpenSSH_2k.log"
      log_format: "<Date> <Day> <Time> <Component> sshd\\[<Pid>\\]: <Content>"
      regex:
          - "(\\d+\\.){3}\\d+"
          - "([\\w-]+\\.){2,}[\\w-]+"
      st: 0.6
      depth: 5
  OpenStack:
      log_file: "OpenStack_2k.log"
      log_format: "<Logrecord> <Date> <Time> <Pid> <Level> <Component> \\[<ADDR>\\] <Content>"
      regex:
          - "((\\d+\\.){3}\\d+,?)+"
          - "/.+?\\s"
          - "\\d+"
      st: 0.5
      depth: 5
  Mac:
      log_file: "Mac_2k.log"
      log_format: "<Month>  <Date> <Time> <User> <Component>\\[<PID>\\]( \\(<Address>\\))?: <Content>"
      regex:
          - "([\\w-]+\\.){2,}[\\w-]+"
      st: 0.7
      depth: 6
  Test:
      log_file: "Test_2k.log"
      log_format: "<Date> <Time>  <Pid>  <Tid> <Level> <Component>: <Content>"
      regex:
        - "(/[\\w-]+)+"
        - "([\\w-]+\\.){2,}[\\w-]+"
        - "\\b(\\-?\\+?\\d+)\\b|\\b0[Xx][a-fA-F\\d]+\\b|\\b[a-fA-F\\d]{4,}\\b"
      st: 0.2
      depth: 6
